spring:
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        show-sql: true
        ddl-auto: create
        format_sql: true
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/   # .html 파일을 불러오기 위한 경로 설정(src/main/resources/templates)
    suffix: .html   # 파일 확장자
    cache: false
  datasource:
    url: jdbc:mariadb://localhost:3307/blog
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
#            redirect-uri: https://kopmorning.com/login/oauth2/code/google
            redirect-url: http://localhost:8080//login/oauth2/code/google
            scope:
              - email
              - profile
jwt:
  issuer: ajufresh@gmail.com
  secret_key: kopmorning-springboot

football:
  api:
    key: ${FOOTBALL_API_KEY}

file:
  ProfileImagePath: C:/Users/wnsgh/img/profile/
  ArticleImagePath: C:/Users/wnsgh/img/article/
#  ProfileImagePath: /img/profile/
#  ArticleImagePath: /img/article/